name: Keep Supabase Active

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Supabase Health Endpoint
        run: |
          curl -sSf ${{ secrets.REACT_APP_SUPABASE_URL }}/rest/v1/ || echo "Ping failed"
