name: Keep Supabase Active

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Health Check Table
        run: |
          curl -sSf -H "apikey: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}" "${{ secrets.REACT_APP_SUPABASE_URL }}/rest/v1/health_check?select=id&limit=1" || echo "Ping failed"
